services:
  airflow-webserver:
    image: apache/airflow:2.7.1
    restart: always
    depends_on:
      - airflow-scheduler
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY="kHpqYEDmzyQPJjLJA3oD3ShX4VNkR6UPZ4t4nRGRAEM="
      - AIRFLOW__WEBSERVER__SECRET_KEY="kHpqYEDmzyQPJjLJA3oD3ShX4VNkR6UPZ4t4nRGRAEM="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - 8080:8080
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1
    restart: always
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CORE__FERNET_KEY="kHpqYEDmzyQPJjLJA3oD3ShX4VNkR6UPZ4t4nRGRAEM="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: scheduler

  airflow-postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./pgdata:/var/lib/postgresql/data
